[package]
name = "aoc3"
version = "0.1.0"
authors = ["Stefan Haubold <sthaubol@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.13"